# Generated by Django 5.2.3 on 2025-06-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_doctorprofile_labattendantprofile_patientprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='address',
            field=models.TextField(blank=True, help_text="Doctor's office address"),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Doctor's contact number", max_length=20),
        ),
        migrations.AddField(
            model_name='labattendantprofile',
            name='address',
            field=models.TextField(blank=True, help_text="Lab's address"),
        ),
        migrations.AddField(
            model_name='labattendantprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Lab's contact number", max_length=20),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='address',
            field=models.TextField(blank=True, help_text="Patient's address"),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='allergies',
            field=models.TextField(blank=True, help_text='Known allergies'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='blood_type',
            field=models.CharField(blank=True, help_text="Patient's blood type", max_length=5),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='current_medications',
            field=models.TextField(blank=True, help_text='Current medications'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='Emergency contact name', max_length=100),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='emergency_phone',
            field=models.CharField(blank=True, help_text='Emergency contact number', max_length=20),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='medical_conditions',
            field=models.TextField(blank=True, help_text='Existing medical conditions'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Patient's contact number", max_length=20),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialty',
            field=models.CharField(blank=True, help_text="Doctor's specialty", max_length=100),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text="Patient's date of birth", null=True),
        ),
    ]
