# Generated by Django 5.2.3 on 2025-06-15 20:20

import django.utils.timezone
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_doctorprofile_address_doctorprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorRegistrationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code', models.CharField(default=users.models.generate_code, max_length=8, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
