# Generated by Django 5.2.3 on 2025-06-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_doctorprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labattendantregistrationcode',
            options={'verbose_name': 'Lab Attendant Registration Code', 'verbose_name_plural': 'Lab Attendant Registration Codes'},
        ),
        migrations.RemoveField(
            model_name='labattendantregistrationcode',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='labattendantregistrationcode',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='labattendantregistrationcode',
            name='used_at',
        ),
        migrations.RemoveField(
            model_name='labattendantregistrationcode',
            name='used_by',
        ),
        migrations.AddField(
            model_name='labattendantregistrationcode',
            name='email',
            field=models.EmailField(default='placeholder@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
