# Generated by Django 5.2.3 on 2025-06-15 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('LAB_RESULT', 'Lab Result'), ('PRESCRIPTION', 'Prescription'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(help_text='Description of the record')),
                ('date', models.DateField(help_text='Date of the record')),
                ('file', models.FileField(blank=True, help_text='Optional file upload (e.g., lab result, report)', null=True, upload_to='medical_records/')),
                ('doctor', models.ForeignKey(blank=True, limit_choices_to={'role': 'DOCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records_as_doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='medical_records_as_patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
