# Generated by Django 5.2.3 on 2025-06-15 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(help_text='Name of the medication', max_length=255)),
                ('dosage', models.CharField(help_text='Dosage information', max_length=100)),
                ('instructions', models.TextField(help_text='Instructions for the patient')),
                ('date_prescribed', models.DateField(help_text='Date prescribed')),
                ('notes', models.TextField(blank=True, help_text='Additional notes (optional)')),
                ('doctor', models.ForeignKey(blank=True, limit_choices_to={'role': 'DOCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_as_doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_as_patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
