# Generated by Django 5.2.3 on 2025-06-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_medication_alter_prescription_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='medication',
            field=models.CharField(default='Unknown', help_text='Medication name', max_length=255),
        ),
    ]
