# Generated by Django 5.2.3 on 2025-06-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_message',
            field=models.TextField(blank=True, help_text='Optional message from the doctor when declining/cancelling.', null=True),
        ),
    ]
