# Generated by Django 5.2.3 on 2025-06-15 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(help_text='Name of the lab test', max_length=100)),
                ('result', models.TextField(help_text='Result of the lab test')),
                ('date', models.DateField(help_text='Date of the lab result')),
                ('file', models.FileField(blank=True, help_text='Optional file upload (e.g., PDF or image of the lab report)', null=True, upload_to='lab_results/')),
                ('lab_attendant', models.ForeignKey(blank=True, limit_choices_to={'role': 'LAB_ATTENDANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results_as_attendant', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='lab_results_as_patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
