# Generated by Django 5.2.3 on 2025-06-15 15:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('turnaround_time', models.IntegerField(help_text='Expected turnaround time in hours')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='labresult',
            options={'ordering': ['-date_ordered', 'priority'], 'permissions': [('can_order_lab_test', 'Can order lab test'), ('can_process_lab_test', 'Can process lab test'), ('can_view_lab_result', 'Can view lab result')]},
        ),
        migrations.RemoveField(
            model_name='labresult',
            name='date',
        ),
        migrations.RemoveField(
            model_name='labresult',
            name='test_name',
        ),
        migrations.AddField(
            model_name='labresult',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labresult',
            name='date_ordered',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='labresult',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_lab_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labresult',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labresult',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or observations'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='priority',
            field=models.IntegerField(default=1, help_text='Priority level from 1 (lowest) to 5 (highest)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='labresult',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='result',
            field=models.TextField(blank=True, help_text='Result of the lab test'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lab.labtest'),
        ),
    ]
