# Generated by Django 5.2.3 on 2025-06-21 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_labtest_alter_labresult_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateField(help_text='Date when the patient wants the test')),
                ('requested_time', models.TimeField(help_text='Time when the patient wants the test')),
                ('reason', models.TextField(help_text='Reason for the test request')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes from lab attendant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='lab_test_requests', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'LAB_ATTENDANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_lab_requests', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab.labtest')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('can_request_lab_test', 'Can request lab test'), ('can_process_lab_request', 'Can process lab request')],
            },
        ),
        migrations.AddField(
            model_name='labresult',
            name='test_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results', to='lab.labtestrequest'),
        ),
    ]
