# Generated by Django 5.2.3 on 2025-06-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmedicalhistory',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientmedicalhistory',
            name='allergies',
            field=models.TextField(blank=True, help_text='List any allergies'),
        ),
        migrations.AddField(
            model_name='patientmedicalhistory',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='patientmedicalhistory',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patientmedicalhistory',
            name='recurrent_illnesses',
            field=models.TextField(blank=True, help_text='List any recurrent illnesses'),
        ),
    ]
